#!/usr/bin/env bash
entries="󰗼 Exit\n Shutdown\n⏾ Suspend\n󰒲 Hibernate\n Reboot"

selected=$(echo -e "$entries"|~/.config/scripts/wmenu-custom menu| awk '{print tolower($2)}')

case "$selected" in
    exit)
        swaymsg exit;;
    shutdown)
        loginctl poweroff;;
    suspend)
        loginctl suspend;;
    hibernate)
        loginctl hibernate;;
    reboot)
        loginctl reboot;;
esac

