vim.cmd.colorscheme("retrobox")

vim.api.nvim_set_hl(0, "Normal",       { bg = "#{{surface}}",                fg = "#{{on_surface}}"                })
vim.api.nvim_set_hl(0, "NormalFloat",  { bg = "#{{surface_container}}",      fg = "#{{on_surface}}"                })
vim.api.nvim_set_hl(0, "FloatBorder",  { bg = "#{{surface_container}}",      fg = "#{{outline}}"                   })
vim.api.nvim_set_hl(0, "Pmenu",        { bg = "#{{surface_container}}",      fg = "#{{on_surface}}"                })
vim.api.nvim_set_hl(0, "PmenuKind",    { bg = "#{{surface_container}}",      fg = "#{{primary}}"                   })
vim.api.nvim_set_hl(0, "PmenuExtra",   { bg = "#{{surface_container}}",      fg = "#{{on_surface_variant}}"        })
vim.api.nvim_set_hl(0, "PmenuSbar",    { bg = "#{{surface_container_low}}",                                        })
vim.api.nvim_set_hl(0, "PmenuThumb",   { bg = "#{{surface_container_high}}",                                       })
vim.api.nvim_set_hl(0, "StatusLine",   { bg = "#{{surface_container}}",      fg = "#{{on_surface}}"                })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "#{{surface_container}}",      fg = "#{{surface_container_highest}}" })
vim.api.nvim_set_hl(0, "CursorLine",   { bg = "#{{surface_variant}}",        fg = "#{{on_surface}}"                })
