vim.cmd("colorscheme retrobox")
vim.cmd("hi Normal guifg=#{{on_surface}} guibg=#{{surface}}")
vim.cmd("hi NormalFloat guibg=#{{surface_container}}")
vim.cmd("hi FloatBorder guifg=#{{outline}} guibg=#{{surface_container}}")
vim.cmd("hi StatusLine guifg=#{{on_primary_container}} guibg=#{{primary_container}}")
vim.cmd("hi StatusLineNC guifg=#{{on_secondary_container}} guibg=#{{secondary_container}}")
vim.cmd("hi SignColumn guibg=#{{surface}}")
vim.cmd("hi CursorLine guibg=#{{surface_variant}}")
vim.cmd("hi Pmenu guifg=#{{on_surface}} guibg=#{{surface_container}}")
vim.cmd("hi PmenuSel guifg=#{{on_primary}} guibg=#{{primary}}")
vim.cmd("hi PmenuMatch guibg=#{{surface_container}}")
vim.cmd("hi PmenuMatchSel guibg=#{{primary}}")
vim.cmd("hi PmenuKind guibg=#{{surface_container}}")
vim.cmd("hi PmenuKindSel guibg=#{{primary}}")
vim.cmd("hi PmenuExtra guibg=#{{surface_container}}")
vim.cmd("hi PmenuExtraSel guibg=#{{primary}}")
vim.cmd("hi PmenuSbar guibg=#{{surface_container_low}}")
vim.cmd("hi PmenuThumb guibg=#{{surface_container_high}}")
